FROM node:20-alpine3.17 as development

WORKDIR /app

COPY package.json ./

# Install esbuild

RUN yarn install

COPY . .

RUN yarn build

FROM node:20-alpine3.17 as staging

WORKDIR /app

COPY --from=development /app/dist ./app

EXPOSE 3031

CMD [ "yarn", "start" ]