FROM node:20-alpine3.17 as development

WORKDIR /app

COPY package.json ./

# Install esbuild

RUN yarn install

COPY . .

RUN yarn build

# FROM development as staging

# COPY --from=development /app/dist/ .

# EXPOSE 3031

CMD [ "yarn", "start" ]