FROM node:20-alpine3.17 as development

WORKDIR /app

COPY package.json ./

# Install esbuild

RUN yarn install


COPY . .

RUN yarn build

EXPOSE 3031


FROM node:20-alpine3.17 as staging

WORKDIR /app

COPY --from=development dist /app

EXPOSE 3031

CMD [ "yarn", "start" ]